#!/bin/sh -x
#
# build and deploy a new version to Google Container Engine
#
# assumes kubectl is configured properly to access GKE.
#
v=`cat app.version`
v=`expr $v + 1`
echo $v > app.version
docker build -t gcr.io/$PROJECT_ID/winelist:v$v .
gcloud docker -- push gcr.io/$PROJECT_ID/winelist:v$v
ed -- deployment.yaml <<EOF
/gcr.io\/kubehack\/winelist/s/v[0-9]*$/v$v/p
w
q
EOF
kubectl delete deployment winelist
kubectl create -f deployment.yaml
